replicaCount: 2
image:
  repository: ghcr.io/dineshuday/fanpulse
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  port: 5000
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi